name: generate-geojson-files
on:
  push:
  schedule:
    - cron: '@weekly'

jobs:
  generate-files:
    name: Generate GeoJson Files
    runs-on: ubuntu-latest

    defaults: # conda needs this
        run:
          shell: bash -l {0}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Conda Python 3.9
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: ox
        python-version: 3.9.2

    - name: Install OSMNX
      run: |
        conda install -c conda-forge osmnx 

    - name: Install other python packages
      run: |
        pip install tqdm
        pip install alphashape

    - name: Fetch API data, filter & convert to geoJson
      run:
        python produce_geojson.py

    - name: Generate VT State polygons
      run: |
        python network_analysis.py

    - name: Generate ESN polygons
      run: |
        python analysis_by_esn.py

    - name: Generate hydrant geometries
      run: |
        python hydrant_analysis.py

    - name: Push 'data' dir with new files to Web repository
      id: push_directory
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'data'
        destination_repo: 'This-blank-Is-On-Fire/This-blank-Is-On-Fire.github.io'
        user_email: 'jcambefort@middlebury.edu'
        user_name: 'johncambefort'
        destination_branch: 'master'